#!/bin/sh
#
# Git hook convenience script for automatically formatting staged files with prettier
#

# Check if this is a merge commit
if [ "$(git rev-parse --verify --quiet MERGE_HEAD)" ]; then
    echo "This is a merge commit, skipping pre-commit checks"
    exit 0
fi

echo "Preparing commit..."

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0
